### User Endpoints

### Регистрация пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.com",
  "avatarUrl": "torrance.png",
  "name": "Jack Torrance",
  "password": "shining"
}

### Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

### Проверка состояния пользователя

GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer dG9yYW5zQG92ZXJsb29rLm5ldDpzaGluaW5n

### Выход из закрытой части приложения

GET http://localhost:5000/users/logout HTTP/1.1
Authorization: Bearer dG9yYW5zQG92ZXJsb29rLm5ldDpzaGluaW5n

### Отправить изображение

POST http://localhost:5000/users/65258514a30fc6ef77c0edef/avatar HTTP/1.1
Content-Type: multipart/form-data;
