### User Endpoints

### Регистрация пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks@htmlacademy.ru",
  "name": "keks",
  "password": "123456",
  "type": "Pro"
}

### Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@htmlacademy.ru",
  "password": "123456"
}

### Проверка состояния пользователя

GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer a2Vrc0BodG1sYWNhZGVteS5ydToxMjM0NTY=

### Выход из закрытой части приложения

GET http://localhost:5000/users/logout HTTP/1.1
Authorization: Bearer ZW1haWwtMUBtYWlsLmNvbToxMjM0NTY

### Отправить изображение

POST http://localhost:5000/users/671fd8bf064064ad6b45c93b/avatar HTTP/1.1
Authorization: Bearer a2Vrc0BodG1sYWNhZGVteS5ydToxMjM0NTY=
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\user\Pictures\screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
